WebApplication/WebApplication/Models/WorkoutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DAL;

namespace WebApplication.Models
{
    public class WorkoutViewModel
    {
        public Workout Workout { get; set; }

        public IEnumerable<WorkoutExercise> WorkoutExercises { get; set; }
    }
}

WebApplication/WebApplication/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Abstract;

namespace WebApplication.Controllers
{
    [Authorize]
    public class WorkoutController : Controller
    {
        private IWorkoutRepository _workoutRepository;

        private User _user;

        public WorkoutController(IWorkoutRepository workoutRepository)
        {
            _workoutRepository = workoutRepository;
        }

        // GET: Workout
        public ActionResult Index()
        {
            SetUp();
            var data = _workoutRepository.GetWorkouts(_user);
            return View(data);
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Workout workout)
        {
            SetUp();
            workout.User = _user;
            workout.Fk_UserId = _user.UserId;

            ModelState.Remove("WorkoutExercises");
            if (ModelState.IsValid)
            {
                _workoutRepository.AddWorkout(workout);
                return RedirectToAction("Index");
            }

            return View(workout);
        }

        public ActionResult Delete(int id)
        {
            Workout workoutToDelete = _workoutRepository.FindWorkout(id);

            if (workoutToDelete != null)
            {
                _workoutRepository.DeleteWorkout(workoutToDelete);
                return RedirectToAction("Index");
            }

            return HttpNotFound("Wrong id");
        }

        private void SetUp()
        {
            string currentUser = HttpContext.User.Identity.Name;
            _user = _workoutRepository.FindUser(currentUser);
        }
    }
}

WebApplication/WebApplication/Controllers/WorkoutExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Abstract;
using Microsoft.AspNet.Identity;
using PagedList;

namespace WebApplication.Controllers
{
    [Authorize]
    public class WorkoutExerciseController : Controller
    {
        private IExerciseRepository _exerciseRepository;
        private IWorkoutRepository _workoutRepository;
        private IUserRepository _userRepository;
        private IWorkoutExerciseRepository _workoutExerciseRepository;
        private User _user;

        public WorkoutExerciseController(IExerciseRepository exerciseRepository, IWorkoutRepository workoutRepository,
            IUserRepository userRepository, IWorkoutExerciseRepository workoutExerciseRepository)
        {
            _exerciseRepository = exerciseRepository;
            _workoutRepository = workoutRepository;
            _userRepository = userRepository;
            _workoutExerciseRepository = workoutExerciseRepository;
        }

        // GET: WorkoutExercise
        public ActionResult Index(int? page)
        {
            SetUser();
            var data = _workoutExerciseRepository.GetExercises(_user);
            var pageNumber = page ?? 1;
            var onePageofData = data.ToPagedList(pageNumber, 5);
            ViewBag.OnePageOfData = onePageofData;

            return View(data);
        }

        public ActionResult Create()
        {
            SetUser();
            ViewBag.ExercisesList = PopulateExercisesSelectList();
            ViewBag.WorkoutsList = PopulateWorkoutSelectList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(WorkoutExercise workoutExercise)
        {
            if (ModelState.IsValid)
            {
                _workoutExerciseRepository.SaveWorkoutExercise(workoutExercise);
                return RedirectToAction("Index", "Workout");
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            WorkoutExercise workoutExerciseToDelete = _workoutExerciseRepository.FindWorkoutExercise(id);

            if (workoutExerciseToDelete != null)
            {
                _workoutExerciseRepository.DeleteWorkoutExercise(workoutExerciseToDelete);
                return RedirectToAction("Index");
            }

            return HttpNotFound("Workout Exercise with specified id does not exist.");
        }

        public ActionResult Edit(int id)
        {
            SetUser();
            WorkoutExercise workoutExercise = _workoutExerciseRepository.FindWorkoutExercise(id);

            ViewBag.ExercisesList = PopulateExercisesSelectList();
            ViewBag.WorkoutsList = PopulateWorkoutSelectList();

            if (workoutExercise != null)
            {
                return View(workoutExercise);
            }

            return HttpNotFound("Workout Exercise with specified id does not exist.");
        }

        [HttpPost]
        public ActionResult Edit(WorkoutExercise workoutExercise)
        {
            if (ModelState.IsValid)
            {
                _workoutExerciseRepository.SaveWorkoutExercise(workoutExercise);
                return RedirectToAction("Index");
            }

            return View(workoutExercise);
        }

        private SelectList PopulateExercisesSelectList()
        {
            var data = from e in _exerciseRepository.GetExercises()
                select new
                {
                    Id = e.ExerciseId,
                    Name = e.Name
                };

            return new SelectList(data, "Id", "Name");
        }

        private SelectList PopulateWorkoutSelectList()
        {
            var data = from w in _workoutRepository.GetWorkouts(_user)
                select new
                {
                    Id = w.WorkoutId,
                    Name = w.Name
                };

            return new SelectList(data, "Id", "Name");
        }

        private void SetUser()
        {
            string userName = HttpContext.User.Identity.GetUserName();
            _user = _userRepository.FindUser(userName);
        }
    }
}

WebApplication/WebApplication/Views/Workout/Create.cshtml
@model DAL.Workout

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Workout</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/WebApplication/Views/Workout/Index.cshtml
@model IEnumerable<DAL.Workout>

@{
    ViewBag.Title = "Index";
}

@Styles.Render("Site.css")

<h2>Workouts</h2>

<p>
    @Html.ActionLink("Add new workout", "Create", null ,new {@class = "btn btn-primary btn-large" })
</p>

<div class="jumbotron">
    @foreach (var item in Model)
    {
        <div>
            <h3>
                <b>
                    @item.Name
                <button class="close" aria-label="Delete" onclick="location.href = '@Url.Action("Delete", "Workout", new {id = @item.WorkoutId})'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </b>

        </h3>
        <table class="table">
            <tr>
                <td colspan="2"><b>Name</b></td>
                <td><b>Sets</b></td>
                <td><b>Reps</b></td>
                <td><b>Kcals burned</b></td>
                <td></td>
            </tr>
            @foreach (var w in item.WorkoutExercises)
            {
                <tr>
                    <td colspan="2">@w.Exercise.Name</td>
                    <td>@w.Sets</td>
                    <td>@w.Reps</td>
                    <td>
                        @{
                            int Const = 25; //5 sets * 5 reps
                            double calsPerRep = @w.Exercise.CaloriesBurned / Const;
                            double burnedCalories = calsPerRep * w.Sets * w.Reps;
                        }
                        @burnedCalories.ToString("F1")
                    </td>
                    <td>
                        <button class="close" aria-label="Delete" onclick="location.href = '@Url.Action("Delete", "WorkoutExercise", new {id = @w.WorkoutExerciseId})'">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </td>
                </tr>
            }

        </table>

    </div>
}
    @Html.ActionLink("Add exercise", "Create", "WorkoutExercise", null, new { @class = "btn btn-primary btn-large" })
</div>