WebApplication/WebApplication/Models/ChartData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication.Models
{
    public class ChartData
    {
        public string[] xValues { get; set; }
        public double[] yValues { get; set; }
        public string seriesName;
    }
}

WebApplication/WebApplication/Models/ChartViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DAL;

namespace WebApplication.Models
{
    public class ChartViewModel
    {
        [Required(ErrorMessage = "Enter amount of data from 1 to 100")]
        [Range(1, 100)]
        [DisplayName("Number of last records")]
        public int AmountOfData { get; set; }

        public IEnumerable<Record> Records { get; set; }

        [Required]
        [DisplayName("Exercise")]
        public int ExerciseId { get; set; }

        public Exercise Exercise { get; set; }
    }
}

WebApplication/WebApplication/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Abstract;
using Microsoft.AspNet.Identity;
using PagedList;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    [Authorize]
    public class RecordController : Controller
    {
        private IRecordRepository _repository;
        private User _user;
        private ChartData _chartData;

        public RecordController(IRecordRepository repository)
        {
            _repository = repository;
            _chartData = new ChartData();
        }

        // GET: Record
        public ActionResult Index()
        {
            SetUser();
            var records = _repository.GetRecords();

            return View(records);
        }

        public ActionResult Get(int? page)
        {
            SetUser();
            var currentUserRecords = _repository.GetRecords(_user);
            var pageNumber = page ?? 1;
            var onePageofData = currentUserRecords.ToPagedList(pageNumber, 5);
            ViewBag.OnePageOfData = onePageofData;

            return View(currentUserRecords);
        }

        public ActionResult Create()
        {
            SetUser();
            ViewBag.ExercisesList = PopulateExercisesSelectList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Record record)
        {
            SetUser();
            record.Fk_UserId = _user.UserId;
            record.User = _user;
            record.Exercise = _repository.FindExercise((int)record.Fk_ExerciseId);

            if (ModelState.IsValid)
            {
                _repository.AddRecord(record);
                return RedirectToAction("Get");
            }

            return View(record);
        }

        public ActionResult Edit(int id)
        {
            SetUser();
            Record recordToEdit = _repository.FindRecord(id);
            ViewBag.ExercisesList = PopulateExercisesSelectList();

            if (recordToEdit == null || recordToEdit.User.Name != _user.Name)
            {
                return HttpNotFound("Invalid record id.");
            }

            return View(recordToEdit);
        }

        [HttpPost]
        public ActionResult Edit(Record record)
        {
            SetUser();
            record.Fk_UserId = _user.UserId;
            record.User = _user;
            record.Exercise = _repository.FindExercise((int)record.Fk_ExerciseId);

            if (ModelState.IsValid)
            {
                _repository.AddRecord(record);
                return RedirectToAction("Get");
            }

            return View(record);
        }

        public ActionResult Delete(int id)
        {
            SetUser();

            Record recordToDelete = _repository.FindRecord(id);

            if (recordToDelete != null && _user.Name == recordToDelete.User.Name)
            {
                _repository.DeleteRecord(recordToDelete);
                return RedirectToAction("Get");
            }

            return HttpNotFound("Something went wrong.");
        }

        private ChartViewModel viewModel;

        public ActionResult Chart()
        {
            _chartData = TempData["data"] as ChartData;

            return View(_chartData);
        }

        public ActionResult ChartData()
        {
            viewModel = new ChartViewModel();
            ViewBag.ExercisesList = PopulateExercisesSelectList();
            ViewBag.AmountValues = GetIntValues();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult ChartData(ChartViewModel chartViewModel)
        {
            SetUser();
            viewModel = new ChartViewModel();
            viewModel.AmountOfData = chartViewModel.AmountOfData;
            viewModel.ExerciseId = chartViewModel.ExerciseId;

            ModelState.Remove("Exercise");
            ModelState.Remove("Records");
            if (ModelState.IsValid)
            {
                viewModel.Exercise = _repository.FindExercise(chartViewModel.ExerciseId);
                viewModel.Records = _repository.GetUserRecords(_user, viewModel.Exercise).Take(viewModel.AmountOfData).OrderBy(r => r.Date);

                if (viewModel.Records == null)
                {
                    return RedirectToAction("ChartData");
                }

                List<string> dates = new List<string>();
                List<double> values = new List<double>();


                foreach (Record record in viewModel.Records)
                {
                    dates.Add(record.Date.Value.ToShortDateString());
                    values.Add(record.WeightLifted);
                }

                _chartData.xValues = dates.ToArray();
                _chartData.yValues = values.ToArray();
                _chartData.seriesName = viewModel.Exercise.Name;

                TempData["data"] = _chartData;

                return RedirectToAction("Chart");
            }

            return View(chartViewModel);
        }

        private SelectList GetIntValues()
        {
            var data = new SelectList(new[]
                {
                    new {Value = 5, Name = "5"},
                    new {Value = 10, Name = "10"},
                    new {Value = 15, Name = "15"}
                },
                "Value", "Name", 1);
            return data;
        }

        private void SetUser()
        {
            string userName = HttpContext.User.Identity.GetUserName();
            _user = _repository.FindUser(userName);
        }

        private SelectList PopulateExercisesSelectList()
        {
            var data = from e in _repository.GetExercises()
                select new
                {
                    Id = e.ExerciseId,
                    Name = e.Name
                };

            return new SelectList(data, "Id", "Name", 1);
        }
    }
}

WebApplication/WebApplication/Views/Record/Chart.cshtml
@model WebApplication.Models.ChartData
@{
    ViewBag.Title = "Chart";
}

<h2>Chart</h2>

@{
    var chart = new Chart(width: 800, height: 600)
        .AddTitle("Records")
        .AddSeries(
            name: @Model.seriesName,
            xValue: @Model.xValues,
            axisLabel: "Date",
            yValues: @Model.yValues,
            chartType: "Spline"
        )
        .SetXAxis("Date")
        .SetYAxis("Weight lifted [kg]")
        .Write();
    
}

WebApplication/WebApplication/Views/Record/ChartData.cshtml
@model WebApplication.Models.ChartViewModel
@{
    ViewBag.Title = "ChartData";
}

<h2>Generate chart</h2>
<p>Select exercise and number of data to be included on the chart. If there is not enough data,
     <br>chart will be created anyway, but it will not have specified amount of data points.</p>

@using (Html.BeginForm("ChartData", "Record", FormMethod.Post, new {target = "_blank"}))
{ 
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ExerciseId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ExerciseId", @ViewBag.ExercisesList as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExerciseId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmountOfData, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("AmountOfData", @ViewBag.AmountValues as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmountOfData, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

WebApplication/WebApplication/Views/Record/Create.cshtml
@model DAL.Record

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Record</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.WeightLifted, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WeightLifted, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WeightLifted, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fk_ExerciseId, "Exercise", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Fk_ExerciseId", (SelectList)@ViewBag.ExercisesList, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Fk_ExerciseId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Get", null, new {@class = "btn btn-primary btn-md"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/WebApplication/Views/Record/Edit.cshtml
@model DAL.Record

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecordId)

        <div class="form-group">
            @Html.LabelFor(model => model.WeightLifted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WeightLifted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WeightLifted, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fk_ExerciseId, "Exercise", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Fk_ExerciseId", (SelectList)@ViewBag.ExercisesList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Fk_ExerciseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Get", null, new {@class = "btn btn-primary btn-md"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication/WebApplication/Views/Record/Get.cshtml
@model IEnumerable<DAL.Record>

@{
    ViewBag.Title = "Get";
}

@using DAL
@using PagedList.Mvc;
@using PagedList;

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>List of records</h2>
<table class="table">
    <tr>
        <td><b>Exercise</b></td>
        <td><b>Weight lifted [kg]</b></td>
        <td><b>Date</b></td>
        <td></td>
    </tr>
    @foreach (Record record in ViewBag.OnePageOfData)
    {
        <tr>
            <td>
                @record.Exercise.Name
            </td>
            <td>
                @record.WeightLifted
            </td>
            <td>
                @record.Date.Value.ToShortDateString()
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = record.RecordId}, new { @class = "btn btn-primary btn-sm" }) 
                @Html.ActionLink("Delete", "Delete", new {id = record.RecordId}, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Add record", "Create", null, new {@class = "btn btn-success btn-large" })
</p>
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfData, page => Url.Action("Get", new { page }))

WebApplication/WebApplication/Views/Record/Index.cshtml
@model IEnumerable<DAL.Record>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.WeightLifted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exercise.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.WeightLifted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exercise.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RecordId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.RecordId })
        </td>
    </tr>
}

</table>